src/main/NKD.Orchard/src/Orchard.Web/Modules/Orchard.DesignerTools/Controllers/AlternateController.cs
using System.IO;
using System.Web.Mvc;
using Orchard.FileSystems.WebSite;
using Orchard.Localization;
using Orchard.Security;
using Orchard.Mvc.Extensions;
using Orchard.Themes;

namespace Orchard.DesignerTools.Controllers {
    [Themed]
    public class AlternateController : Controller {
        private readonly IWebSiteFolder _webSiteFolder;
        private readonly IThemeManager _themeManager;

        public AlternateController(IOrchardServices orchardServices, IWebSiteFolder webSiteFolder, IThemeManager themeManager) {
            _webSiteFolder = webSiteFolder;
            _themeManager = themeManager;
            Services = orchardServices;
        }

        public IOrchardServices Services { get; set; }
        public Localizer T { get; set; }

        public ActionResult Create(string template, string alternate, string returnUrl) {
            if (!Request.IsLocal && !Services.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to create templates")))
                return new HttpUnauthorizedResult();

            alternate = alternate.Replace("__", "-").Replace("_", ".");

            var currentTheme = _themeManager.GetRequestTheme(Request.RequestContext);
            var alternateFilename = Server.MapPath(Path.Combine(currentTheme.Location, currentTheme.Id, "Views", alternate));
            var isCodeTemplate = template.Contains("::");

            // use same extension as template, or ".cshtml" if it's a code template))
            if (!isCodeTemplate && _webSiteFolder.FileExists(template)) {
                alternateFilename += Path.GetExtension(template);

                using (var stream = System.IO.File.Create(alternateFilename)) {
                    _webSiteFolder.CopyFileTo(template, stream);
                }
            }
            else {
                alternateFilename += ".cshtml";
                using (System.IO.File.Create(alternateFilename)) { }
            }

            return this.RedirectLocal(returnUrl);
        }
    }
}

src/main/NKD.Orchard/src/Orchard.Web/Modules/Orchard.DesignerTools/Views/ShapeTracingMeta.cshtml
@using Orchard.Utility.Extensions;
@using Orchard.DesignerTools.Services;

@functions {
    string FormatShapeName(string shape) {
        string shapeType = Model.ShapeType;
        string displayType = Model.DisplayType;
        
        if(!String.IsNullOrWhiteSpace(displayType)) {
            if(shape.StartsWith(shapeType + "_" + displayType)) {
                shape = shapeType + shape.Substring(shapeType.Length + displayType.Length + 1) + "_" + displayType; 
            }
        }
        
        return shape.Replace("__", "-").Replace("_", ".");
    }
    
    string FormatShapeFilename(string shape, string themeId) {
        shape = FormatShapeName(shape);
        return "~/Themes/" + themeId + "/Views/" + shape.Replace("__", "-").Replace("_", ".") + ".cshtml";
    }
    
    string RemoveBeacons(string htmlContent) {
        var regex = new System.Text.RegularExpressions.Regex(@"<script\sclass=""shape-tracing-wrapper(.*?)</script>");
        return regex.Replace(htmlContent, String.Empty);
    }

    string RemoveEmptyLines(string htmlContent) {
        var regex = new System.Text.RegularExpressions.Regex(@"[\r\n]+");
        return regex.Replace(htmlContent, System.Environment.NewLine);
    }
}


<script type="text/javascript">
shapeTracingMetadataHost[@Model.ShapeId] = {};

shapeTracingMetadataHost[@Model.ShapeId].shape = { 
    type: '@Model.ShapeType', 
    template: '@Model.Template', 
    originalTemplate: '@Model.OriginalTemplate',
    displayType: '@(String.IsNullOrEmpty((string)Model.DisplayType) ? T("n/a").Text : Model.DisplayType.ToString())',
    position: '@(String.IsNullOrEmpty((string)Model.Position) ? T("n/a").Text : Model.Position.ToString())',
    placement: '@(String.IsNullOrEmpty((string)Model.PlacementSource) ? T("n/a").Text : Model.PlacementSource.ToString())',
    alternates: [
        @foreach (var alternate in (new[] { (string)Model.ShapeType }).Concat((List<string>)Model.Alternates))
        {
        <text>{</text>
        <text>filename: '@FormatShapeFilename(alternate, WorkContext.CurrentTheme.Id)',</text>
        <text>alternate: '@FormatShapeName(alternate)',</text> 
        <text>template: '@Model.Template',</text>
        <text>returnUrl: '@Context.Request.RawUrl'</text>
        <text>},</text>
        }
    ],
    wrappers: [
        @foreach (var wrapper in Model.Wrappers) {
            if (wrapper == "ShapeTracingWrapper") { continue; }
        <text>{ filename: '@FormatShapeFilename(wrapper, WorkContext.CurrentTheme.Id)' },
        </text>
        }
    ],
    html: '@Html.Raw(ShapeTracingFactory.FormatJsonValue(RemoveEmptyLines(RemoveBeacons(Display(Model.ChildContent).ToString()))))',
    templateContent: '@Html.Raw(ShapeTracingFactory.FormatJsonValue(String.IsNullOrWhiteSpace((string)Model.TemplateContent) ? @T("Content not available as coming from source code.").ToString() : (string)Model.TemplateContent))',
    model: { @(new MvcHtmlString((string)@Model.Dump)) }
};

@if (!String.IsNullOrEmpty((string)Model.PlacementSource) && (WorkContext.HttpContext.Items[(string)Model.PlacementSource] == null)) {
    WorkContext.HttpContext.Items[(string)Model.PlacementSource] = new object();
<text>shapeTracingMetadataHost.placement['@Model.PlacementSource.ToString()'] = '@HttpUtility.JavaScriptStringEncode((string)Model.PlacementContent)'; </text>
}

</script>

src/main/NKD.Orchard/src/Orchard.Web/Modules/Orchard.DesignerTools/Views/ShapeTracingTemplates.cshtml
<div id="shape-tracing-container"> 
    <div id="shape-tracing-resize-handle" ></div>
    <div id="shape-tracing-toolbar">
        <div id="shape-tracing-toolbar-switch"></div>
    </div>
    <div id="shape-tracing-window">
        <div id="shape-tracing-window-tree"></div>
        <div id="shape-tracing-window-content">
            <ul id="shape-tracing-tabs">
                <li id="shape-tracing-tabs-shape" class="selected first">@T("Shape")</li>
                <li id="shape-tracing-tabs-model" class="middle">@T("Model")</li>
                <li id="shape-tracing-tabs-placement" class="middle">@T("Placement")</li>
                <li id="shape-tracing-tabs-template" class="middle">@T("Template")</li>
                <li id="shape-tracing-tabs-html" class="last">@T("HTML")</li>
            </ul>
            <div id="shape-tracing-breadcrumb"></div>
            <div id="shape-tracing-meta-content"></div>
        </div>
    </div>
</div>
<div id="shape-tracing-container-ghost"></div>
<div id="shape-tracing-overlay"></div>

<script id="shape-tracing-tabs-shape-template" type="text/x-jquery-tmpl">
    <div class="shape grid-display">
        <ul class="properties">
            <li class="sgd-s"><div class="name">@T("Shape").Text</div><div class="value">${shape.type}</div></li>
            <li class="sgd-t"><div class="name">@T("Active Template").Text</div><div class="value"><a id="activeTemplate" href="#">${shape.template}</a></div></li>
            {{if shape.template != shape.originalTemplate}}
            <li class="sgd-ot"><div class="name">@T("Original Template").Text Template</div><div class="value">${shape.originalTemplate}</div></li>
            {{/if}}
            <li class="sgd-d"><div class="name">@T("Display Type").Text</div><div class="value">${shape.displayType}</div></li>
            <li class="sgd-a"><div class="name">@T("Alternate ({0})", "${shape.alternates.length}").Text</div>
                <div class="value">&nbsp;</div>
                <ul>
                {{each shape.alternates}}
                    <li>
                        <div class="name">
                        @using (Html.BeginFormAntiForgeryPost(Url.Action("Create", "Alternate", new { Area = "Orchard.DesignerTools" }), FormMethod.Post, new { @class = "inline link" }))
                        { 
                            @Html.Hidden("Alternate", "${$value.alternate}")
                            @Html.Hidden("Template", "${$value.template}")
                            @Html.Hidden("ReturnUrl", "${$value.returnUrl}")
                            <button type="submit" class="create-template">@T("Create").Text</button>
                        }
                        </div>
                        <div class="value">${$value.filename}</div>
                    </li>
                {{/each}}
                </ul>
            </li>
            <li class="sgd-w"><div class="name">@T("Wrappers ({0})", "${shape.wrappers.length}")</div>
                <div class="value">&nbsp;</div>
                <ul>
                {{each shape.wrappers}}
                    <li><div class="name">&nbsp;</div><div class="value">${$value.filename}</div></li>
                {{/each}}
                </ul>
            </li>
        </ul>
    </div>
</script>

<script id="shape-tracing-tabs-model-template" type="text/x-jquery-tmpl">
    <div class="model grid-display">
        <ul>{{tmpl "#shape-tracing-tabs-model-node-template"}}</ul>
    </div>
</script>

<script id="shape-tracing-tabs-model-node-template" type="text/x-jquery-tmpl">
    <li>
        <div class="name">${name}</div>
        <div class="value">${value}</div>
        {{if children}}
            <ul style="display:none">
                {{tmpl(children) "#shape-tracing-tabs-model-node-template"}}
            </ul>
        {{/if}}
    </li>
</script>

<script id="shape-tracing-tabs-placement-template" type="text/x-jquery-tmpl">
    <div class="placement">
        <textarea>${$data}</textarea>
    </div>
</script>

<script id="shape-tracing-tabs-template-template" type="text/x-jquery-tmpl">
    <div class="template">
        <textarea>${$data}</textarea>
    </div>
</script>

<script id="shape-tracing-tabs-html-template" type="text/x-jquery-tmpl">
    <div class="html">
        <textarea>${$data}</textarea>
    </div>
</script>

src/main/NKD.Orchard/src/Orchard.Web/Modules/Orchard.DesignerTools/Views/ShapeTracingWrapper.cshtml
@{
    if (Model.IgnoreShapeTracer != null && (bool)Model.IgnoreShapeTracer) {
        @Display(Model.Metadata.ChildContent)
        return;
    }
    
    Script.Require("jQueryUI").AtHead();
    Script.Include("orchard-designertools-shapetracing.js").AtHead();
    Script.Include("jquery.scrollTo-1.4.4.min.js").AtHead();
    Style.Include("orchard-designertools-shapetracing.css");
    
    // Code Mirror
    Script.Include("CodeMirror/codemirror.js");
    Style.Include("CodeMirror/codemirror.css");
    Script.Include("CodeMirror/razor.js");
    Style.Include("CodeMirror/razor.css");
    Script.Include("CodeMirror/javascript.js");
    Style.Include("CodeMirror/javascript.css");
    Script.Include("CodeMirror/css.js");
    Style.Include("CodeMirror/css.css");
    Script.Include("CodeMirror/htmlmixed.js");
    
    Script.Include("jquery.tmpl.min.js");
}

<script class="shape-tracing-wrapper" shape-id="@Model.ShapeId" shape-type="@Model.Metadata.Type" shape-hint="@Model.Hint"></script>@Display(Model.Metadata.ChildContent)<script class="shape-tracing-wrapper" end-of="@Model.ShapeId"></script>
    @{
        Layout.Zones["Tail"].Add(
            New.ShapeTracingMeta(
                ShapeType: Model.Metadata.Type,
                Template: Model.Template,
                OriginalTemplate: Model.OriginalTemplate,
                TemplateContent: Model.TemplateContent, 
                DisplayType: Model.Metadata.DisplayType, 
                Position: Model.Metadata.Position, 
                PlacementSource: Model.Metadata.PlacementSource, 
                PlacementContent: Model.PlacementContent, 
                Alternates: Model.Metadata.Alternates, 
                Wrappers: Model.Metadata.Wrappers, 
                ChildContent: Model.Metadata.ChildContent,
                ShapeId: Model.ShapeId,
                Dump: Model._Dump
        ));
    }